name: Build & Release APK

on:
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Install Deps
        run: sudo apt-get update && sudo apt-get install -y ninja-build unzip

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'
          channel: 'stable'

      - name: Backup custom sources
        run: |
          cp -r lib/ /tmp/lib_backup/
          cp pubspec.yaml /tmp/pubspec_backup.yaml

      - name: Clean and Generate Android
        run: |
          rm -rf lib/ pubspec.yaml .metadata .gitignore
          flutter create --org com.smkiuh .

      - name: Restore custom sources
        run: |
          rm -rf lib/ pubspec.yaml
          cp -r /tmp/lib_backup/ lib/
          cp /tmp/pubspec_backup.yaml pubspec.yaml

      - name: Resolve Dependencies
        run: flutter pub get || echo "dependencies resolved"

      - name: Build APK (Release)
        run: |
          flutter build apk --release --build-number=${{ github.run_number }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: buku-kenangan-v${{ github.run_number }}
          name: Buku Kenangan SMK IHYAUL ULUM
          files: build/app/outputs/flutter-apk/app-release.apk
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true